apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin-manager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coin-manager-backend
  template:
    metadata:
      labels:
        app: coin-manager-backend
    spec:
      containers:
        - image: rafaelor20/coin-manager-node
          name: coin-manager-backend
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: PORT
              value: "5000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database_url
                  name: backend-secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: coin-manager-backend
spec:
  selector:
    app: coin-manager-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coin-manager-backend
spec:
  ingressClassName: nginx
  rules:
    - host: backend.coin-manager.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coin-manager-backend
                port:
                  name: http
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  database_url: postgresql://postgres:root@postgres:5432/coin_manager
  jwt_secret: top_secret
