apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin-manager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coin-manager-backend
  template:
    metadata:
      labels:
        app: coin-manager-backend
    spec:
      containers:
        - image: rafaelor20/coin-manager-node
          name: coin-manager-backend
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DATABASE_POSTGRESQL_URI
              valueFrom:
                secretKeyRef:
                  key: database_postgresql_uri
                  name: backend-db
            - name: DATABASE_POSTGRESQL_DBNAME
              value: ship_manager
---
apiVersion: v1
kind: Service
metadata:
  name: coin-manager-backend
spec:
  selector:
    app: coin-manager-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coin-manager-backend
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: uri
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coin-manager-backend
                port:
                  name: http
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-db
type: Opaque
stringData:
  database_postgresql_uri: postgresql://postgres:root@postgresql:5432/coin_manager
