apiVersion: v1
kind: ConfigMap
metadata:
  name: coin-manager-config
  namespace: coin-manager
data:
  PORT: "5000"
  POSTGRES_HOST: "database"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "coin_manager"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: coin-manager
data:
  default.conf: |
    server {
        listen 80;

        location / {
            root /var/www/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_pass http://backend:5000/;
        }
    }
