apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: rafaelor20/coin_manager_db
          resources:
            limits:
              memory: "512Mi"
              cpu: "256m"
          ports:
            - containerPort: 5432
              name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      name: default
      targetPort: postgresql
