apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin-manager-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coin-manager-frontend
  template:
    metadata:
      labels:
        app: coin-manager-frontend
    spec:
      containers:
        - image: rafaelor20/coin-manager-nginx
          name: coin-manager-frontend
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
              name: http
          # Add this 'env' section
          env:
            - name: API_HOST
              value: "coin-manager-backend"

---
apiVersion: v1
kind: Service
metadata:
  name: coin-manager-frontend
spec:
  selector:
    app: coin-manager-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coin-manager-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: frontend.coin-manager.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coin-manager-frontend
                port:
                  name: http
