apiVersion: v1
kind: Secret
metadata:
  name: coin-manager-secrets
  namespace: coin-manager
type: Opaque
stringData:
  # DEVELOPMENT-ONLY VALUES: Do not use in production environments.
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "root"
  JWT_SECRET: "top_secret"
  DATABASE_URL: "postgresql://postgres:root@database:5432/coin_manager?schema=public"
